package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	targetFile := "/tmp/claude-spawn-poc.md"
	os.Remove(targetFile) // Clean slate

	prompt := `Create a markdown file at /tmp/claude-spawn-poc.md with exactly this content:
# Claude Spawn POC
Generated by Claude CLI spawned from Go binary.
This proves Go can orchestrate Claude sessions.`

	// Spawn Claude with tool permissions for non-interactive execution
	cmd := exec.Command("claude", "--dangerously-skip-permissions", "-p", prompt)
	output, err := cmd.CombinedOutput()

	fmt.Printf("Claude output:\n%s\n", output)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	// Verify file was created
	if content, err := os.ReadFile(targetFile); err == nil {
		fmt.Printf("\n✓ SUCCESS: File created!\n---\n%s---\n", content)
		os.Exit(0)
	}
	fmt.Println("\n✗ FAILURE: File not created")
	os.Exit(1)
}
